version: '3'

services:
  db:
    restart: always
    image: mdillon/postgis:9.3
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
  app:
    env_file: .env
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    volumes:
      - .:/code
    links:
      - db:db
    ports:
      - "8000:8000"
    depends_on:
      - db
