version: '3'

services:
  db:
    restart: always
    image: mdillon/postgis:9.3
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
  queue:
    hostname: queue
    image: rabbitmq:3.6-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
  app:
    env_file: .env
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    links:
      - db:db
    ports:
      - "8000:8000"
    depends_on:
      - db
