version: '3'

services:
  db:
    restart: always
    image: mdillon/postgis:9.6-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
  app:
    environment:
      DATABASE_URL: postgis://postgres@db:5432/postgres
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      args:
        DJANGO_REQUIREMENTS: production
    command: /code/compose/django/gunicorn.sh
    links:
      - db:db
    ports:
      - "8000:8000"
    depends_on:
      - db

# http://vsupalov.com/docker-env-vars/
